bash "/content/Final_Stem_Creator/1.move-rename-start.sh"
bash "/content/Final_Stem_Creator/2.cover.sh"
node "/content/Final_Stem_Creator/5.stemai.js"  >  "/content/Final_Stem_Creator/6.convert.sh"
bash "/content/Final_Stem_Creator/7.executar.sh"
bash "/content/Final_Stem_Creator/8.move-rename-end.sh"
